name: Learning GitHub Script

on: workflow_dispatch

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Count pull requests with "CI-long-timeout" label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const query = `query($owner:String!, $name:String!, $label:String!) {
              repository(owner:$owner, name:$name) {
                pullRequests(last:100, states:OPEN, labels: [$label]) {
                  totalCount
                }
              }
            }`;
            const variables = {
              owner: 'Homebrew',
              name: 'homebrew-core',
              label: 'CI-long-timeout'
            }
            const result = await github.graphql(query, variables)
            console.log(result)

            const { repository: { pullRequests: { totalCount } } } = result
            github.issues.createComment({
              issue_number: 10,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: String(totalCount).concat(" pull requests with the 'CI-long-timeout' label.")
            })
