name: Remove issue label

on: workflow_dispatch

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Count pull requests with "CI-long-timeout" label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabels({
              issue_number: 10,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug']
            })
