name: Triage tasks

on: pull_request

jobs:
  timeout_labels:
    runs-on: ubuntu-latest
    outputs:
      long-pr-count: ${{ steps.count.outputs.count }}
    steps:
      - name: Count pull requests with the `CI-long-timeout` label
        if: contains(github.event.issue.labels.*.name, 'bug')
        id: count_long_timeout_prs
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `query($owner:String!, $name:String!, $label:String!) {
              repository(owner:$owner, name:$name){
                issues(first:100, states:OPEN, labels: [$label]) {
                  totalCount
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              label: 'bug'
            }
            const { repository: { issues: { totalCount } } }  = await github.graphql(query, variables)
            core.setOutput('count', totalCount)

            if (totalCount > 2) {
              core.setFailed(`Too many pull requests (${totalCount}) with the long-timeout label!`)
            }

      - name: Remove `CI-long-timeout` label if applicable
        if: fromJson(steps.count_long_timeout_prs.outputs.count) >= 2
        uses: Homebrew/actions/label-pull-requests@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          def: |
            - label: bug
              path: nonexistent/path/hack
